#!/bin/sh

set -e

if ! [ -x "$(command -v ansible)" ]; then
  echo "Installing Ansible"
  sudo dnf install ansible -y
fi

ansible-galaxy collection install community.general
ansible-playbook --ask-become-pass playbook.yaml
