---
- name: Install Appstream metadata
  become: yes
  shell: dnf groupupdate core -y

- name: Install multimedia packages
  become: yes
  shell: dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y

- name: Install sound-and-video complement packages
  become: yes
  shell: dnf groupupdate sound-and-video -y

- name: Check if KDE Plasma is installed
  package_facts:
    manager: "auto"

- name: Add kup repo if KDE Plasma is installed
  become: yes
  get_url:
    url: https://download.opensuse.org/repositories/home:/simper:/kup/Fedora_Rawhide/home:simper:kup.repo
    dest: /etc/yum.repos.d/
  when: "'plasma-desktop' in ansible_facts.packages" 

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest

- name: Install DNF packages
  become: yes
  dnf:
    name: "{{ dnf_package }}"
    state: present

- name: Attempt to install KDE packages
  become: yes
  dnf:
    name: "{{ kde_package }}"
    state: present
  when: "'plasma-desktop' in ansible_facts.packages"

- name: Remove packages
  become: yes
  dnf:
    name: "{{ remove }}"
    state: absent
    autoremove: yes

- name: Add the flathub flatpak repo
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install flatpak packages
  flatpak:
    name: "{{ flatpak }}"
    state: present
    method: user

- name: Install Joplin
  shell: wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
