---
- name: Set zsh as default shell
  user: name={{ lookup('env', 'USER') }} shell=/usr/bin/zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  register: status
  failed_when: 
    - " 'The $ZSH folder already exists' not in status.stderr "
    - status.stderr != ''

- name: Install Powerlevel10k
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-{{ ansible_env.HOME }}/.oh-my-zsh/custom}/themes/powerlevel10k

- name: Create font directory
  file:
    path: /usr/local/share/fonts/m
    state: directory

- name: Download MesloLGS NF fonts 1
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
    dest: /usr/local/share/fonts/m/MesloLGSNFRegular.ttf 

- name: Download MesloLGS NF fonts 2
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
    dest: /usr/local/share/fonts/m/MesloLGSNFBold.ttf

- name: Download MesloLGS NF fonts 3
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
    dest: /usr/local/share/fonts/m/MesloLGSNFItalic.ttf

- name: Download MesloLGS NF fonts 4
  get_url:
    url: https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
    dest: /usr/local/share/fonts/m/MesloLGSNFBoldItalic.ttf